// =============================================================================
// Tests for seg_argmax Halide generator
// =============================================================================
//
// Test strategy:
//   Unlike image processing ops (resize, blur) which have OpenCV equivalents,
//   there is no direct OpenCV function for "argmax across channels." Instead,
//   we verify against a plain C++ reference implementation.
//
//   Since argmax is an exact integer operation (no interpolation or rounding),
//   the Halide output must match the reference EXACTLY -- zero tolerance.
//
// Test cases:
//   1. MatchesReference    - Random logits, verify against C++ argmax
//   2. KnownPattern        - Deterministic dominant channel per pixel
//   3. UniformInput        - All channels equal, verify tie-breaking
//   4. SingleDominantChannel - Each class as sole winner across entire image
//
// All tests are parametrized across 6 resolutions including odd sizes
// (641x481, 1279x719) to verify TailStrategy::GuardWithIf correctness.
// =============================================================================

#include "test_common.h"

// This header is AUTO-GENERATED by the Halide AOT compiler.
// It declares: int seg_argmax(halide_buffer_t* input, halide_buffer_t* output)
// The Halide::Runtime::Buffer<T> wrapper auto-converts to halide_buffer_t*.
#include "seg_argmax.h"

#include <cstdlib>
#include <cmath>

static const int NUM_CLASSES = 8;

// ---------------------------------------------------------------------------
// Test data generator: random logits
// ---------------------------------------------------------------------------
// Creates a planar float32 buffer simulating segmentation model output.
//
// Halide::Runtime::Buffer<float>(width, height, num_classes) creates a
// 3D buffer with PLANAR layout by default:
//   - dim 0 (x): stride = 1          (adjacent pixels are contiguous)
//   - dim 1 (y): stride = width      (rows are contiguous)
//   - dim 2 (c): stride = width*height (each class plane is contiguous)
//
// Memory layout for a 4x3 image with 8 classes:
//   [class0: 12 floats][class1: 12 floats]...[class7: 12 floats]
//
// Values range from -5.0 to +5.0, mimicking typical model logit ranges.
static Halide::Runtime::Buffer<float> make_random_logits(int width, int height, unsigned seed) {
    Halide::Runtime::Buffer<float> buf(width, height, NUM_CLASSES);
    std::srand(seed);
    for (int c = 0; c < NUM_CLASSES; c++)
        for (int y = 0; y < height; y++)
            for (int x = 0; x < width; x++)
                buf(x, y, c) = (float)(std::rand() % 10000) / 1000.0f - 5.0f;
    return buf;
}

// ---------------------------------------------------------------------------
// C++ reference implementation
// ---------------------------------------------------------------------------
// This is the "ground truth" for testing. It implements the exact same
// algorithm as the Halide generator:
//   - Initialize with class 0
//   - For each subsequent class, update if strictly greater (>)
//   - Tie-breaking: lowest class index wins (because > requires strictly greater)
//
// IMPORTANT: The comparison operator must match the Halide generator exactly.
// If the generator used >=, the HIGHEST class index would win ties instead.
static Halide::Runtime::Buffer<uint8_t> reference_argmax(
    const Halide::Runtime::Buffer<float>& input, int num_classes) {
    // dim(0).extent() returns the size of dimension 0 (width)
    int w = input.dim(0).extent();
    int h = input.dim(1).extent();
    Halide::Runtime::Buffer<uint8_t> result(w, h);
    for (int y = 0; y < h; y++) {
        for (int x = 0; x < w; x++) {
            float max_val = input(x, y, 0);
            uint8_t max_idx = 0;
            for (int c = 1; c < num_classes; c++) {
                if (input(x, y, c) > max_val) {
                    max_val = input(x, y, c);
                    max_idx = static_cast<uint8_t>(c);
                }
            }
            result(x, y) = max_idx;
        }
    }
    return result;
}

// GoogleTest parameterized test fixture.
// Each test case runs once per resolution defined in INSTANTIATE_TEST_SUITE_P.
class SegArgmaxTest : public ::testing::TestWithParam<std::pair<int, int>> {};

// ---------------------------------------------------------------------------
// Test 1: Random logits vs C++ reference
// ---------------------------------------------------------------------------
// The most comprehensive test. Uses pseudo-random data (fixed seed=42 for
// reproducibility) to cover a wide range of value combinations.
// Exact match expected -- argmax has no rounding or approximation.
TEST_P(SegArgmaxTest, Argmax_MatchesReference) {
    auto [width, height] = GetParam();

    auto input_buf = make_random_logits(width, height, 42);
    auto ref = reference_argmax(input_buf, NUM_CLASSES);

    // Allocate output buffer for Halide. Buffer<uint8_t>(w, h) creates
    // a 2D planar buffer (stride(0)=1, stride(1)=width).
    Halide::Runtime::Buffer<uint8_t> output_buf(width, height);

    // Call the AOT-compiled Halide function. Returns 0 on success.
    // The function signature comes from seg_argmax.h:
    //   int seg_argmax(halide_buffer_t* input, halide_buffer_t* output)
    // Halide::Runtime::Buffer<T> implicitly converts to halide_buffer_t*.
    int err = seg_argmax(input_buf, output_buf);
    ASSERT_EQ(err, 0) << "Halide seg_argmax failed with error " << err;

    int mismatches = 0;
    for (int y = 0; y < height; y++) {
        for (int x = 0; x < width; x++) {
            if (output_buf(x, y) != ref(x, y)) {
                mismatches++;
            }
        }
    }
    EXPECT_EQ(mismatches, 0)
        << "Argmax should be exact (no rounding), got " << mismatches << " mismatches";
}

// ---------------------------------------------------------------------------
// Test 2: Known deterministic pattern
// ---------------------------------------------------------------------------
// For each pixel, channel (x+y)%8 is set to 10.0 (dominant), all others to -1.0.
// This creates a checkerboard-like pattern across all 8 classes, verifying
// that the generator correctly indexes into each channel.
TEST_P(SegArgmaxTest, Argmax_KnownPattern) {
    auto [width, height] = GetParam();

    Halide::Runtime::Buffer<float> input_buf(width, height, NUM_CLASSES);
    for (int c = 0; c < NUM_CLASSES; c++)
        for (int y = 0; y < height; y++)
            for (int x = 0; x < width; x++)
                input_buf(x, y, c) = (c == (x + y) % NUM_CLASSES) ? 10.0f : -1.0f;

    Halide::Runtime::Buffer<uint8_t> output_buf(width, height);
    int err = seg_argmax(input_buf, output_buf);
    ASSERT_EQ(err, 0);

    int mismatches = 0;
    for (int y = 0; y < height; y++) {
        for (int x = 0; x < width; x++) {
            uint8_t expected = static_cast<uint8_t>((x + y) % NUM_CLASSES);
            if (output_buf(x, y) != expected) {
                mismatches++;
            }
        }
    }
    EXPECT_EQ(mismatches, 0) << "Known pattern mismatch";
}

// ---------------------------------------------------------------------------
// Test 3: Uniform input (tie-breaking verification)
// ---------------------------------------------------------------------------
// All 8 channels have the identical value (1.0). Since the Halide generator
// uses strict greater-than (>), later channels CANNOT beat earlier ones when
// equal. Therefore class 0 always wins.
//
// This is a critical edge case: if the generator incorrectly used >= instead
// of >, the result would be class 7 (last writer wins), which this test catches.
TEST_P(SegArgmaxTest, Argmax_UniformInput) {
    auto [width, height] = GetParam();

    Halide::Runtime::Buffer<float> input_buf(width, height, NUM_CLASSES);
    for (int c = 0; c < NUM_CLASSES; c++)
        for (int y = 0; y < height; y++)
            for (int x = 0; x < width; x++)
                input_buf(x, y, c) = 1.0f;

    Halide::Runtime::Buffer<uint8_t> output_buf(width, height);
    int err = seg_argmax(input_buf, output_buf);
    ASSERT_EQ(err, 0);

    for (int y = 0; y < height; y++) {
        for (int x = 0; x < width; x++) {
            ASSERT_EQ(output_buf(x, y), 0)
                << "Uniform input should yield class 0 at (" << x << "," << y << ")";
        }
    }
}

// ---------------------------------------------------------------------------
// Test 4: Single dominant channel sweep
// ---------------------------------------------------------------------------
// For each of the 8 classes, set ONLY that class to 100.0 and all others to 0.0.
// Verifies that the generator correctly identifies each possible class index.
// This catches bugs where specific channel indices might be skipped or misordered.
TEST_P(SegArgmaxTest, Argmax_SingleDominantChannel) {
    auto [width, height] = GetParam();

    for (int dominant = 0; dominant < NUM_CLASSES; dominant++) {
        Halide::Runtime::Buffer<float> input_buf(width, height, NUM_CLASSES);
        for (int c = 0; c < NUM_CLASSES; c++)
            for (int y = 0; y < height; y++)
                for (int x = 0; x < width; x++)
                    input_buf(x, y, c) = (c == dominant) ? 100.0f : 0.0f;

        Halide::Runtime::Buffer<uint8_t> output_buf(width, height);
        int err = seg_argmax(input_buf, output_buf);
        ASSERT_EQ(err, 0) << "Failed for dominant class " << dominant;

        for (int y = 0; y < height; y++) {
            for (int x = 0; x < width; x++) {
                ASSERT_EQ(output_buf(x, y), dominant)
                    << "Expected class " << dominant << " at (" << x << "," << y << ")";
            }
        }
    }
}

// Parametrize all tests across multiple resolutions.
// Odd sizes (641x481, 1279x719) verify that TailStrategy::GuardWithIf
// correctly handles the case when width % vectorize_factor != 0.
// For vectorize(x, 8): 641 % 8 = 1, so the last pixel group has only 1 pixel.
INSTANTIATE_TEST_SUITE_P(
    Resolutions,
    SegArgmaxTest,
    ::testing::Values(
        std::make_pair(320, 240),
        std::make_pair(640, 480),
        std::make_pair(641, 481),
        std::make_pair(1280, 720),
        std::make_pair(1279, 719),
        std::make_pair(1920, 1080)
    )
);
