// =============================================================================
// Halide Operation Wrappers — Implementation
// =============================================================================
//
// This file implements thin wrapper functions that delegate to AOT-generated
// Halide functions. Each #include below pulls in a header generated by Halide's
// AOT compiler, which declares a plain C function (e.g., `int nv21_to_rgb(...)`).
//
// The `::` prefix (e.g., `::nv21_to_rgb`) calls the GLOBAL function from the
// generated header, distinguishing it from `halide_ops::nv21_to_rgb` (this
// wrapper in the halide_ops namespace).
//
// Halide::Runtime::Buffer<T> automatically converts to halide_buffer_t*
// (the C struct that AOT-generated functions actually expect). This conversion
// is zero-copy — it just passes the internal pointer, no data is copied.
//
// =============================================================================

#include "halide_ops.h"

// ---------------------------------------------------------------------------
// Generated Halide AOT headers
// ---------------------------------------------------------------------------
// Each header declares one C function with halide_buffer_t* parameters.
// The function name matches the `-f` flag used during AOT compilation:
//   ./bin/generator -g <generator_name> -f <function_name> target=arm-64-android ...
#include "rgb_bgr_convert.h"
#include "nv21_to_rgb.h"
#include "gaussian_blur_y.h"
#include "gaussian_blur_rgb.h"
#include "lens_blur.h"
#include "resize_bilinear.h"
#include "resize_bicubic.h"
#include "resize_bilinear_target.h"
#include "resize_bicubic_target.h"
#include "rotate_fixed_90cw.h"
#include "rotate_fixed_180.h"
#include "rotate_fixed_270cw.h"
#include "rotate_arbitrary.h"
#include "rgb_to_nv21.h"
#include "resize_area.h"
#include "resize_area_target.h"
#include "resize_letterbox.h"
#include "flip_horizontal.h"
#include "flip_vertical.h"
// Fused NV21 pipeline variants — one per rotation angle per resize method.
// rotation_code is a compile-time GeneratorParam, so each angle requires
// a separately AOT-compiled function. The dispatch helpers below select
// the correct variant at runtime based on the rotation_degrees_cw argument.
#include "nv21_pipeline_bilinear_none.h"
#include "nv21_pipeline_bilinear_90cw.h"
#include "nv21_pipeline_bilinear_180.h"
#include "nv21_pipeline_bilinear_270cw.h"
#include "nv21_pipeline_area_none.h"
#include "nv21_pipeline_area_90cw.h"
#include "nv21_pipeline_area_180.h"
#include "nv21_pipeline_area_270cw.h"
#include "seg_argmax.h"
#include "nv21_yuv444_rgb.h"
#include "nv21_to_rgb_full_range.h"
#include "nv21_resize_pad_rotate_none.h"
#include "nv21_resize_pad_rotate_90cw.h"
#include "nv21_resize_pad_rotate_180.h"
#include "nv21_resize_pad_rotate_270cw.h"

namespace halide_ops {

// ---------------------------------------------------------------------------
// Color Space Conversions
// ---------------------------------------------------------------------------

int rgb_bgr(Halide::Runtime::Buffer<uint8_t>& input,
            Halide::Runtime::Buffer<uint8_t>& output) {
    // The generated function is named "rgb_bgr_convert" (not "rgb_bgr")
    // to avoid collision with this wrapper function name.
    return rgb_bgr_convert(input, output);
}

int nv21_to_rgb(Halide::Runtime::Buffer<uint8_t>& y_plane,
                Halide::Runtime::Buffer<uint8_t>& uv_plane,
                Halide::Runtime::Buffer<uint8_t>& output) {
    // :: prefix calls the global AOT-generated function, not this wrapper.
    return ::nv21_to_rgb(y_plane, uv_plane, output);
}

int nv21_yuv444_rgb(Halide::Runtime::Buffer<uint8_t>& y_plane,
                    Halide::Runtime::Buffer<uint8_t>& uv_plane,
                    Halide::Runtime::Buffer<uint8_t>& output) {
    return ::nv21_yuv444_rgb(y_plane, uv_plane, output);
}

int nv21_to_rgb_full_range(Halide::Runtime::Buffer<uint8_t>& y_plane,
                           Halide::Runtime::Buffer<uint8_t>& uv_plane,
                           Halide::Runtime::Buffer<uint8_t>& output) {
    return ::nv21_to_rgb_full_range(y_plane, uv_plane, output);
}

// ---------------------------------------------------------------------------
// Blur Operations
// ---------------------------------------------------------------------------

int gaussian_blur_gray(Halide::Runtime::Buffer<uint8_t>& input,
                       Halide::Runtime::Buffer<uint8_t>& output) {
    // "gaussian_blur_y" is the AOT function name — "y" refers to the Y plane
    // (grayscale), not the y-axis. The generator class is GaussianBlurY.
    return gaussian_blur_y(input, output);
}

int gaussian_blur_rgb(Halide::Runtime::Buffer<uint8_t>& input,
                      Halide::Runtime::Buffer<uint8_t>& output) {
    return ::gaussian_blur_rgb(input, output);
}

int lens_blur(Halide::Runtime::Buffer<uint8_t>& input,
              int radius,
              Halide::Runtime::Buffer<uint8_t>& output) {
    // The runtime radius is passed as a scalar parameter to the AOT function.
    // It must be <= max_radius (8), which was the compile-time GeneratorParam
    // that sized the RDom (reduction domain) in the generator.
    return ::lens_blur(input, radius, output);
}

// ---------------------------------------------------------------------------
// Resize Operations (scale-factor variants)
// ---------------------------------------------------------------------------

int resize_bilinear(Halide::Runtime::Buffer<uint8_t>& input,
                    float scale_x, float scale_y,
                    Halide::Runtime::Buffer<uint8_t>& output) {
    return ::resize_bilinear(input, scale_x, scale_y, output);
}

int resize_bicubic(Halide::Runtime::Buffer<uint8_t>& input,
                   float scale_x, float scale_y,
                   Halide::Runtime::Buffer<uint8_t>& output) {
    return ::resize_bicubic(input, scale_x, scale_y, output);
}

// ---------------------------------------------------------------------------
// Fixed Rotations
// ---------------------------------------------------------------------------

int rotate_90cw(Halide::Runtime::Buffer<uint8_t>& input,
                Halide::Runtime::Buffer<uint8_t>& output) {
    return ::rotate_fixed_90cw(input, output);
}

int rotate_180(Halide::Runtime::Buffer<uint8_t>& input,
               Halide::Runtime::Buffer<uint8_t>& output) {
    return ::rotate_fixed_180(input, output);
}

int rotate_270cw(Halide::Runtime::Buffer<uint8_t>& input,
                 Halide::Runtime::Buffer<uint8_t>& output) {
    return ::rotate_fixed_270cw(input, output);
}

// Counter-clockwise aliases: CCW and CW are inverses that sum to 360.
//   90  CCW = 360 - 90  = 270 CW
//   270 CCW = 360 - 270 = 90  CW
int rotate_90ccw(Halide::Runtime::Buffer<uint8_t>& input,
                 Halide::Runtime::Buffer<uint8_t>& output) {
    return ::rotate_fixed_270cw(input, output);
}

int rotate_270ccw(Halide::Runtime::Buffer<uint8_t>& input,
                  Halide::Runtime::Buffer<uint8_t>& output) {
    return ::rotate_fixed_90cw(input, output);
}

// Legacy alias — assumes clockwise direction.
int rotate_90(Halide::Runtime::Buffer<uint8_t>& input,
              Halide::Runtime::Buffer<uint8_t>& output) {
    return ::rotate_fixed_90cw(input, output);
}

// ---------------------------------------------------------------------------
// Arbitrary Rotation
// ---------------------------------------------------------------------------

int rotate_angle(Halide::Runtime::Buffer<uint8_t>& input,
                 float angle_rad,
                 Halide::Runtime::Buffer<uint8_t>& output) {
    return ::rotate_arbitrary(input, angle_rad, output);
}

// ---------------------------------------------------------------------------
// RGB to NV21
// ---------------------------------------------------------------------------

int rgb_to_nv21(Halide::Runtime::Buffer<uint8_t>& input,
                Halide::Runtime::Buffer<uint8_t>& y_output,
                Halide::Runtime::Buffer<uint8_t>& uv_output) {
    return ::rgb_to_nv21(input, y_output, uv_output);
}

// ---------------------------------------------------------------------------
// Area Resize and Letterbox
// ---------------------------------------------------------------------------

int resize_area(Halide::Runtime::Buffer<uint8_t>& input,
                float scale_x, float scale_y,
                Halide::Runtime::Buffer<uint8_t>& output) {
    return ::resize_area(input, scale_x, scale_y, output);
}

int resize_letterbox(Halide::Runtime::Buffer<uint8_t>& input,
                     int target_w, int target_h,
                     Halide::Runtime::Buffer<uint8_t>& output) {
    return ::resize_letterbox(input, target_w, target_h, output);
}

// ---------------------------------------------------------------------------
// Target-size Resize APIs
// ---------------------------------------------------------------------------

int resize_bilinear_target(Halide::Runtime::Buffer<uint8_t>& input,
                           int target_w, int target_h,
                           Halide::Runtime::Buffer<uint8_t>& output) {
    return ::resize_bilinear_target(input, target_w, target_h, output);
}

int resize_bicubic_target(Halide::Runtime::Buffer<uint8_t>& input,
                          int target_w, int target_h,
                          Halide::Runtime::Buffer<uint8_t>& output) {
    return ::resize_bicubic_target(input, target_w, target_h, output);
}

int resize_area_target(Halide::Runtime::Buffer<uint8_t>& input,
                       int target_w, int target_h,
                       Halide::Runtime::Buffer<uint8_t>& output) {
    return ::resize_area_target(input, target_w, target_h, output);
}

// ---------------------------------------------------------------------------
// Flip Operations
// ---------------------------------------------------------------------------

int flip_horizontal(Halide::Runtime::Buffer<uint8_t>& input,
                    Halide::Runtime::Buffer<uint8_t>& output) {
    return ::flip_horizontal(input, output);
}

int flip_vertical(Halide::Runtime::Buffer<uint8_t>& input,
                  Halide::Runtime::Buffer<uint8_t>& output) {
    return ::flip_vertical(input, output);
}

// ---------------------------------------------------------------------------
// Fused NV21 Pipeline Dispatch Helpers
// ---------------------------------------------------------------------------
//
// Each rotation angle is a separately AOT-compiled function because
// rotation_code is a compile-time GeneratorParam (baked into the generated
// code). This eliminates runtime branching inside the hot pixel loop —
// the compiler can fully optimize the coordinate transform for each angle.
//
// The flip_code is a runtime parameter (near-zero cost: single select per pixel).
//
// These dispatch helpers map a runtime rotation_degrees_cw value to the
// correct AOT variant. Returns -1 for invalid rotation angles.

// Dispatch bilinear fused pipeline by rotation angle
static int dispatch_nv21_bilinear(Halide::Runtime::Buffer<uint8_t>& y,
                                  Halide::Runtime::Buffer<uint8_t>& uv,
                                  int rotation_cw, int flip,
                                  int tw, int th,
                                  Halide::Runtime::Buffer<uint8_t>& out) {
    switch (rotation_cw) {
        case 0:   return ::nv21_pipeline_bilinear_none(y, uv, flip, tw, th, out);
        case 90:  return ::nv21_pipeline_bilinear_90cw(y, uv, flip, tw, th, out);
        case 180: return ::nv21_pipeline_bilinear_180(y, uv, flip, tw, th, out);
        case 270: return ::nv21_pipeline_bilinear_270cw(y, uv, flip, tw, th, out);
        default:  return -1;  // Invalid rotation angle
    }
}

// Dispatch INTER_AREA fused pipeline by rotation angle
static int dispatch_nv21_area(Halide::Runtime::Buffer<uint8_t>& y,
                              Halide::Runtime::Buffer<uint8_t>& uv,
                              int rotation_cw, int flip,
                              int tw, int th,
                              Halide::Runtime::Buffer<uint8_t>& out) {
    switch (rotation_cw) {
        case 0:   return ::nv21_pipeline_area_none(y, uv, flip, tw, th, out);
        case 90:  return ::nv21_pipeline_area_90cw(y, uv, flip, tw, th, out);
        case 180: return ::nv21_pipeline_area_180(y, uv, flip, tw, th, out);
        case 270: return ::nv21_pipeline_area_270cw(y, uv, flip, tw, th, out);
        default:  return -1;  // Invalid rotation angle
    }
}

// ---------------------------------------------------------------------------
// Fused NV21 Pipeline Public API
// ---------------------------------------------------------------------------

int nv21_rotate_resize_rgb(Halide::Runtime::Buffer<uint8_t>& y_plane,
                           Halide::Runtime::Buffer<uint8_t>& uv_plane,
                           int rotation_degrees_cw,
                           int target_w, int target_h,
                           Halide::Runtime::Buffer<uint8_t>& output) {
    // No flip (flip_code=0) — rotation + bilinear resize only
    return dispatch_nv21_bilinear(y_plane, uv_plane, rotation_degrees_cw,
                                 0, target_w, target_h, output);
}

int nv21_rotate_flip_resize_rgb(Halide::Runtime::Buffer<uint8_t>& y_plane,
                                Halide::Runtime::Buffer<uint8_t>& uv_plane,
                                int rotation_degrees_cw, int flip_code,
                                int target_w, int target_h,
                                Halide::Runtime::Buffer<uint8_t>& output) {
    return dispatch_nv21_bilinear(y_plane, uv_plane, rotation_degrees_cw,
                                 flip_code, target_w, target_h, output);
}

int nv21_rotate_resize_area_rgb(Halide::Runtime::Buffer<uint8_t>& y_plane,
                                Halide::Runtime::Buffer<uint8_t>& uv_plane,
                                int rotation_degrees_cw,
                                int target_w, int target_h,
                                Halide::Runtime::Buffer<uint8_t>& output) {
    // No flip (flip_code=0) — rotation + area resize only
    return dispatch_nv21_area(y_plane, uv_plane, rotation_degrees_cw,
                              0, target_w, target_h, output);
}

int nv21_rotate_flip_resize_area_rgb(Halide::Runtime::Buffer<uint8_t>& y_plane,
                                     Halide::Runtime::Buffer<uint8_t>& uv_plane,
                                     int rotation_degrees_cw, int flip_code,
                                     int target_w, int target_h,
                                     Halide::Runtime::Buffer<uint8_t>& output) {
    return dispatch_nv21_area(y_plane, uv_plane, rotation_degrees_cw,
                              flip_code, target_w, target_h, output);
}

// ---------------------------------------------------------------------------
// Fused NV21 -> Resize -> Pad -> Rotate Dispatch
// ---------------------------------------------------------------------------

static int dispatch_nv21_resize_pad_rotate(Halide::Runtime::Buffer<uint8_t>& y,
                                           Halide::Runtime::Buffer<uint8_t>& uv,
                                           int rotation_cw, int target_size,
                                           Halide::Runtime::Buffer<uint8_t>& out) {
    switch (rotation_cw) {
        case 0:   return ::nv21_resize_pad_rotate_none(y, uv, target_size, out);
        case 90:  return ::nv21_resize_pad_rotate_90cw(y, uv, target_size, out);
        case 180: return ::nv21_resize_pad_rotate_180(y, uv, target_size, out);
        case 270: return ::nv21_resize_pad_rotate_270cw(y, uv, target_size, out);
        default:  return -1;
    }
}

int nv21_resize_pad_rotate(Halide::Runtime::Buffer<uint8_t>& y_plane,
                           Halide::Runtime::Buffer<uint8_t>& uv_plane,
                           int rotation_degrees_cw,
                           int target_size,
                           Halide::Runtime::Buffer<uint8_t>& output) {
    return dispatch_nv21_resize_pad_rotate(y_plane, uv_plane,
                                           rotation_degrees_cw, target_size, output);
}

// ---------------------------------------------------------------------------
// Segmentation Argmax
// ---------------------------------------------------------------------------

// Find the class with the highest logit per pixel.
//
// The :: prefix calls the global function generated by Halide AOT compilation
// (declared in "seg_argmax.h"), distinguishing it from this wrapper function
// which lives in the halide_ops namespace.
//
// Halide::Runtime::Buffer<T> automatically converts to halide_buffer_t*
// (the C struct that the AOT-generated function actually expects).
// This conversion is zero-copy — it just passes the internal pointer.
int seg_argmax(Halide::Runtime::Buffer<float>& input,
               Halide::Runtime::Buffer<uint8_t>& output) {
    return ::seg_argmax(input, output);
}

} // namespace halide_ops
